### PR TITLE
try to read the host from hosts file first

### PR DESCRIPTION
**Pull request by tedder**
Flipped the conditional logic and stepping through getent and s6-dnsip4 to try to grab the address. Note the colon is a bash no-op.

### CODE REVIEW

**Comment by mikenye** [comment]
Hi @tedder,

Thanks for this.

I have a question - is there any reason why you're using `getent ahosts` instead of `getent hosts` ?

It looks like if we used `getent hosts` we can remove the pipes to `head`/`cut` etc...

-Mike

**Comment by tedder** [comment]
..because I didn't know about `hosts`. It allows us to get rid of the `head`, which is good, but it still returns the full row, meaning `cut` is necessary:
```
# getent hosts beast
172.17.0.2      beast 8abb5dbbfd90 dump1090
```

**Review by mikenye — APPROVED** [review]

**Comment by mikenye** [comment]
Thanks for this! I'm running the `docker build` process now.

I appreciate your contribution. :-)

**Comment by mikenye** [comment]
New images are built and pushed.

**Pull request merged**
